apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tvhtvrjxh-go 
  janus-idp.io/tekton: tvhtvrjxh-go
  backstage.io/kubernetes-id: tvhtvrjxh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tvhtvrjxh-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml